# Generated by Django 4.2.6 on 2023-10-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_review_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="star",
            field=models.IntegerField(
                blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], null=True
            ),
        ),
    ]
