# Generated by Django 4.2.6 on 2023-10-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(
                blank=True,
                default="media/userProfile/default.png",
                null=True,
                upload_to="media/userProfile",
            ),
        ),
    ]
